### ISSUE TITLE
Better management of transcriptions

### ISSUE THREAD

**Issue by yprie** [yprie/uPMT#30]
being able to modify name, date, etc.
Being able to see a summary table for all the transcriptions

**Comment by Thykof** [comment]
Since https://github.com/yprie/uPMT/releases/tag/v0.4.0, you can edit the interview: change the name of the participant, the date and the comment. You can't change the text of the transcription.

At the bottom of the left panel, there is the list of the interview with participant name and date.
This may be viewed as a "summary table".
